openapi: 3.0.0
info:
  title: Food Delivery API
  description: API documentation for the Food Delivery application.
  version: 1.0.0
servers:
  - url: http://locahost:8000
    description: Local server
  - url: ${{server}}
    description: Production server
